### ISSUE TITLE
Insufficiently wide char code on some platforms

### ISSUE THREAD

**Issue by maandree** [tomolt/libschrift#4]
Both C and POSIX only specifies that `int` must be at least 16 bits wide (Linux says 32 bits), so `charCode` in `stf_char` should either be an `uint_least32_t`, an `unsigned long int`, or a `long int` (`uint32_t` could also be used if you only care for normal computers).

**Comment by tomolt** [comment]
I'd like to avoid using overly specific integer types where possible, so I'm definitely in favour of `unsigned long`.

**Comment by tomolt** [comment]
Done as of eeefd2f.
