### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by Condzi** [tomolt/libschrift#8]
Hello! I had to add following code to make compiling in C++ possible. I think it should be added to the library.
In _schrift.h_:
```cpp
// Just before first struct declarations
#ifdef __cplusplus
extern "C" {
#endif

// (schrift.h code here...)

// Before the last #endif
#ifdef __cplusplus
}
#endif
```

**Comment by tomolt** [comment]
Hi, I just want to let you know that this going into the library as soon as I have the time.

**Comment by tomolt** [comment]
Done as of b48359e (on the v0.8 branch only).
